/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development': RouteRecordInfo<
      '/development',
      '/development',
      Record<never, never>,
      Record<never, never>,
      | '/development/'
      | '/development/button'
      | '/development/checkbox'
      | '/development/divider'
      | '/development/getting-started'
      | '/development/input'
      | '/development/modal'
      | '/development/panel'
      | '/development/popover'
      | '/development/portrait'
      | '/development/progress'
      | '/development/radio'
      | '/development/resource-bar'
      | '/development/select'
      | '/development/slider'
      | '/development/tab'
      | '/development/tag'
      | '/development/theming'
      | '/development/toast'
      | '/development/tooltip'
      | '/development/unit-bar'
    >,
    '/development/': RouteRecordInfo<
      '/development/',
      '/development',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/button': RouteRecordInfo<
      '/development/button',
      '/development/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/checkbox': RouteRecordInfo<
      '/development/checkbox',
      '/development/checkbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/divider': RouteRecordInfo<
      '/development/divider',
      '/development/divider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/getting-started': RouteRecordInfo<
      '/development/getting-started',
      '/development/getting-started',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/input': RouteRecordInfo<
      '/development/input',
      '/development/input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/modal': RouteRecordInfo<
      '/development/modal',
      '/development/modal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/panel': RouteRecordInfo<
      '/development/panel',
      '/development/panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/popover': RouteRecordInfo<
      '/development/popover',
      '/development/popover',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/portrait': RouteRecordInfo<
      '/development/portrait',
      '/development/portrait',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/progress': RouteRecordInfo<
      '/development/progress',
      '/development/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/radio': RouteRecordInfo<
      '/development/radio',
      '/development/radio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/resource-bar': RouteRecordInfo<
      '/development/resource-bar',
      '/development/resource-bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/select': RouteRecordInfo<
      '/development/select',
      '/development/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/slider': RouteRecordInfo<
      '/development/slider',
      '/development/slider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/tab': RouteRecordInfo<
      '/development/tab',
      '/development/tab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/tag': RouteRecordInfo<
      '/development/tag',
      '/development/tag',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/theming': RouteRecordInfo<
      '/development/theming',
      '/development/theming',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/toast': RouteRecordInfo<
      '/development/toast',
      '/development/toast',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/tooltip': RouteRecordInfo<
      '/development/tooltip',
      '/development/tooltip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/development/unit-bar': RouteRecordInfo<
      '/development/unit-bar',
      '/development/unit-bar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development.vue': {
      routes:
        | '/development'
        | '/development/'
        | '/development/button'
        | '/development/checkbox'
        | '/development/divider'
        | '/development/getting-started'
        | '/development/input'
        | '/development/modal'
        | '/development/panel'
        | '/development/popover'
        | '/development/portrait'
        | '/development/progress'
        | '/development/radio'
        | '/development/resource-bar'
        | '/development/select'
        | '/development/slider'
        | '/development/tab'
        | '/development/tag'
        | '/development/theming'
        | '/development/toast'
        | '/development/tooltip'
        | '/development/unit-bar'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/development/index.vue': {
      routes:
        | '/development/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/button.vue': {
      routes:
        | '/development/button'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/checkbox.vue': {
      routes:
        | '/development/checkbox'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/divider.vue': {
      routes:
        | '/development/divider'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/getting-started.vue': {
      routes:
        | '/development/getting-started'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/input.vue': {
      routes:
        | '/development/input'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/modal.vue': {
      routes:
        | '/development/modal'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/panel.vue': {
      routes:
        | '/development/panel'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/popover.vue': {
      routes:
        | '/development/popover'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/portrait.vue': {
      routes:
        | '/development/portrait'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/progress.vue': {
      routes:
        | '/development/progress'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/radio.vue': {
      routes:
        | '/development/radio'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/resource-bar.vue': {
      routes:
        | '/development/resource-bar'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/select.vue': {
      routes:
        | '/development/select'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/slider.vue': {
      routes:
        | '/development/slider'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/tab.vue': {
      routes:
        | '/development/tab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/tag.vue': {
      routes:
        | '/development/tag'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/theming.vue': {
      routes:
        | '/development/theming'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/toast.vue': {
      routes:
        | '/development/toast'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/tooltip.vue': {
      routes:
        | '/development/tooltip'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/development/unit-bar.vue': {
      routes:
        | '/development/unit-bar'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
